### PR TITLE
Improve code highlighting, fix for #28

### PR DESCRIPTION
**Pull request by paulsiersma**

### CODE REVIEW

**Comment by paulsiersma** [comment]
image

**Comment by bastiaanb** [comment]
Code preview looks good now, except that `arduino.h` is still lower case. Forgot to update the `leaphy-blocky` dependency?
I lack the expertise to properly review the code, so I have added @jeroenoomsNL  as reviewer.

**Comment by paulsiersma** [comment]
@bastiaanb I was planning of submitting a separate PR for updating the blockly dependency. I wouldn't want that update getting blocked on something I did wrong in fixing the code highlighting.

**Comment by bastiaanb** [comment]
> @bastiaanb I was planning of submitting a separate PR for updating the blockly dependency. I wouldn't want that update getting blocked on something I did wrong in fixing the code highlighting.

Ah, ok, I got a bit confused with the number for this pr (#29) the same as the issue in leaphy-blockly.
I have approved, based on behaviour and how the code looks, but may @jeroenoomsNL also wants to have a look?

**Review by bastiaanb — APPROVED** [review]
LGTM

**Pull request merged**
